# Generated by Django 5.2.11 on 2026-02-19 00:18

import core.models
import django.db.models.deletion
import django.utils.timezone
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('access_mode', models.CharField(choices=[('closed', 'Closed — invite only'), ('public', 'Public — self-service access')], default='closed', max_length=10)),
                ('scim_id', models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'dataset',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('scim_id', models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'dsg_group',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('google_sub', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('gdpr_consent', models.BooleanField(default=False)),
                ('pi', models.CharField(blank=True, default='', max_length=255)),
                ('read_only', models.BooleanField(default=False)),
                ('scim_id', models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dsg_user',
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, default=core.models._generate_token, max_length=128, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_key',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=255)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255)),
                ('gcs_bucket', models.CharField(blank=True, default='', max_length=255)),
                ('prefix', models.CharField(blank=True, default='', max_length=512)),
                ('is_public', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.dataset')),
            ],
            options={
                'db_table': 'dataset_version',
                'unique_together': {('dataset', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Added by admin or lab head'), ('self_service', 'Self-service TOS acceptance')], default='manual', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='core.dataset')),
                ('dataset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='core.datasetversion')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permission')),
            ],
            options={
                'db_table': 'grant',
            },
        ),
        migrations.CreateModel(
            name='ServiceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=255)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tables', to='core.dataset')),
            ],
            options={
                'db_table': 'service_table',
                'unique_together': {('service_name', 'table_name')},
            },
        ),
        migrations.CreateModel(
            name='TOSDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('invite_token', models.CharField(default=secrets.token_urlsafe, help_text='Unguessable token for TOS page URLs on closed datasets', max_length=64, unique=True)),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('retired_date', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tos_documents', to='core.dataset')),
                ('dataset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tos_documents', to='core.datasetversion')),
            ],
            options={
                'db_table': 'tos_document',
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='tos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='core.tosdocument'),
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='core.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_group',
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='users', through='core.UserGroup', to='core.group'),
        ),
        migrations.CreateModel(
            name='DatasetAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='core.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dataset_admin',
                'unique_together': {('user', 'dataset')},
            },
        ),
        migrations.CreateModel(
            name='GroupDatasetPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='core.dataset')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_permissions', to='core.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permission')),
            ],
            options={
                'db_table': 'group_dataset_permission',
                'unique_together': {('group', 'dataset', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='PublicRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_id', models.BigIntegerField()),
                ('service_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_roots', to='core.servicetable')),
            ],
            options={
                'db_table': 'public_root',
                'unique_together': {('service_table', 'root_id')},
            },
        ),
        migrations.CreateModel(
            name='TOSAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tos_acceptances', to=settings.AUTH_USER_MODEL)),
                ('tos_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='core.tosdocument')),
            ],
            options={
                'db_table': 'tos_acceptance',
                'unique_together': {('user', 'tos_document')},
            },
        ),
    ]
