# Generated by Django 5.2.11 on 2026-02-23 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_set_site_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='core.group'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='source',
            field=models.CharField(choices=[('manual', 'Added by admin or team lead'), ('self_service', 'Self-service TOS acceptance')], default='manual', max_length=20),
        ),
    ]
