# Generated by Django 5.2.11 on 2026-03-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_set_site_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='source',
            field=models.CharField(choices=[('manual', 'Added by admin'), ('self_service', 'Self-service TOS acceptance')], default='manual', max_length=20),
        ),
    ]
