# Generated by Django 5.2.11 on 2026-03-11 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_datasetbucket_m2m_remove_gcs_bucket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('base_url', models.URLField(blank=True, default='')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.AddField(
            model_name='tosdocument',
            name='service',
            field=models.ForeignKey(blank=True, help_text='If set, this TOS is required only when accessing via this service', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tos_documents', to='core.service'),
        ),
    ]
