# Generated by Django 5.2.11 on 2026-04-17 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_service_model_and_tos_service_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'affiliation',
                'unique_together': {('user', 'name')},
            },
        ),
    ]
