# Generated by Django 5.2.11 on 2026-04-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_notes_and_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture_url',
            field=models.URLField(blank=True, default='', max_length=512),
        ),
    ]
