# Generated by Django 5.2.11 on 2026-04-17 02:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=core.models._default_expiry, null=True),
        ),
    ]
