# Generated by Django 5.2.11 on 2026-05-08 02:57

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_apikey_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_accounts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_account',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAccountToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, default=core.models._generate_token, max_length=128, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('service_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='core.serviceaccount')),
            ],
            options={
                'db_table': 'service_account_token',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAccountGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_account_grants', to='core.dataset')),
                ('dataset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_account_grants', to='core.datasetversion')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sa_grants_given', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permission')),
                ('service_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='core.serviceaccount')),
            ],
            options={
                'db_table': 'service_account_grant',
                'unique_together': {('service_account', 'dataset', 'dataset_version', 'permission')},
            },
        ),
    ]
