# Generated by Django 5.2.11 on 2026-07-08 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_serviceaccount_serviceaccounttoken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dataset_alias',
            },
        ),
        migrations.AlterUniqueTogether(
            name='groupdatasetpermission',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='serviceaccountgrant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='branch',
            field=models.CharField(default='main', max_length=255),
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='ordinal',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='buckets',
            field=models.ManyToManyField(blank=True, related_name='grants', to='core.datasetbucket'),
        ),
        migrations.AddField(
            model_name='grant',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='core.service'),
        ),
        migrations.AddField(
            model_name='groupdatasetpermission',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='core.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='version_eval_mode',
            field=models.CharField(choices=[('linear', 'Linear'), ('dag', 'DAG')], default='linear', max_length=10),
        ),
        migrations.AddField(
            model_name='serviceaccountgrant',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_account_grants', to='core.service'),
        ),
        migrations.AddConstraint(
            model_name='datasetversion',
            constraint=models.UniqueConstraint(condition=models.Q(('ordinal__isnull', False)), fields=('dataset', 'branch', 'ordinal'), name='uniq_dataset_version_dataset_branch_ordinal'),
        ),
        migrations.AddConstraint(
            model_name='groupdatasetpermission',
            constraint=models.UniqueConstraint(condition=models.Q(('service__isnull', True)), fields=('group', 'dataset', 'permission'), name='uniq_group_dataset_permission_null_service'),
        ),
        migrations.AddConstraint(
            model_name='groupdatasetpermission',
            constraint=models.UniqueConstraint(condition=models.Q(('service__isnull', False)), fields=('group', 'dataset', 'service', 'permission'), name='uniq_group_dataset_permission_service'),
        ),
        migrations.AddConstraint(
            model_name='serviceaccountgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('dataset_version__isnull', True), ('service__isnull', True)), fields=('service_account', 'dataset', 'permission'), name='uniq_sa_grant_dataset_null_service_null_version'),
        ),
        migrations.AddConstraint(
            model_name='serviceaccountgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('dataset_version__isnull', False), ('service__isnull', True)), fields=('service_account', 'dataset', 'dataset_version', 'permission'), name='uniq_sa_grant_dataset_null_service_version'),
        ),
        migrations.AddConstraint(
            model_name='serviceaccountgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('dataset_version__isnull', True), ('service__isnull', False)), fields=('service_account', 'dataset', 'service', 'permission'), name='uniq_sa_grant_dataset_service_null_version'),
        ),
        migrations.AddConstraint(
            model_name='serviceaccountgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('dataset_version__isnull', False), ('service__isnull', False)), fields=('service_account', 'dataset', 'dataset_version', 'service', 'permission'), name='uniq_sa_grant_dataset_service_version'),
        ),
        migrations.AddField(
            model_name='datasetalias',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.dataset'),
        ),
        migrations.AddField(
            model_name='datasetalias',
            name='dataset_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.datasetversion'),
        ),
        migrations.AddField(
            model_name='datasetalias',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_aliases', to='core.service'),
        ),
        migrations.AddConstraint(
            model_name='datasetalias',
            constraint=models.UniqueConstraint(fields=('service', 'client_name', 'client_version'), name='uniq_dataset_alias_service_name_version'),
        ),
        migrations.AddConstraint(
            model_name='datasetalias',
            constraint=models.UniqueConstraint(condition=models.Q(('client_version__isnull', True)), fields=('service', 'client_name'), name='uniq_dataset_alias_service_name_null_version'),
        ),
    ]
