# Generated by Django 5.2.11 on 2026-07-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_datasetalias_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BucketIAMBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bucket_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "bucket_iam_binding",
            },
        ),
        migrations.AddConstraint(
            model_name="bucketiambinding",
            constraint=models.UniqueConstraint(
                fields=("bucket_name", "email"),
                name="uniq_bucket_iam_binding_bucket_email",
            ),
        ),
        migrations.AddIndex(
            model_name="bucketiambinding",
            index=models.Index(fields=["bucket_name"], name="bucket_iam_bucket_idx"),
        ),
        migrations.AddIndex(
            model_name="bucketiambinding",
            index=models.Index(fields=["email"], name="bucket_iam_email_idx"),
        ),
    ]
