# Generated by Django 5.2.11 on 2026-08-10, then hand-edited to add the
# fail-closed precondition below.

from django.db import migrations


def check_no_parented_users(apps, schema_editor):
    """Refuse to drop the column while any user-type service account exists.

    The removal was justified on a live count of zero parented rows, but that
    was a *snapshot*, not a protected invariant: Django admin's UserAdmin
    excluded only `password`, so it auto-included the editable `parent` FK and
    an administrator could mint a parented row at any time up to this
    migration. Re-check at apply time rather than trust the reading — a
    surviving row would otherwise be silently unlinked by the drop.
    """
    User = apps.get_model("core", "User")
    orphaned = User.objects.filter(parent_id__isnull=False)
    count = orphaned.count()
    if count:
        emails = list(orphaned.values_list("email", flat=True)[:10])
        raise RuntimeError(
            f"Refusing to drop dsg_user.parent_id: {count} user-type service "
            f"account(s) still exist (first {len(emails)}: {', '.join(emails)}). "
            "Migrate them to dedicated ServiceAccount rows, or delete them, "
            "then re-run. See sessions/changes/"
            "datasets-0019-remove-user-type-service-accounts.md."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_bucketiambinding"),
    ]

    operations = [
        # Guard first: RemoveField is irreversible for the data it unlinks.
        migrations.RunPython(check_no_parented_users, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="user",
            name="parent",
        ),
    ]
