# Generated by Django 5.2.11 on 2026-08-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_user_parent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email__iendswith', '@service-account.dsg.local'), _negated=True), name='user_email_not_service_account_domain'),
        ),
    ]
