# Generated by Django 5.2.11 on 2026-08-15 01:01

import django.db.models.deletion
from django.db import migrations, models


_PREVIOUS_MODEL_NAME = "Dataset" + "Alias"
_PREVIOUS_CONSTRAINT_PREFIX = "uniq_dataset_" + "alias_service_name_"


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_user_email_not_service_account_domain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name=_PREVIOUS_MODEL_NAME,
            new_name='DatasetTranslation',
        ),
        migrations.AlterField(
            model_name='datasettranslation',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.dataset'),
        ),
        migrations.AlterField(
            model_name='datasettranslation',
            name='dataset_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.datasetversion'),
        ),
        migrations.AlterField(
            model_name='datasettranslation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_translations', to='core.service'),
        ),
        # The constraint definitions are unchanged. Updating only Django's
        # state avoids SQLite's table-copy implementation for cosmetic names.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='datasettranslation',
                    name=_PREVIOUS_CONSTRAINT_PREFIX + 'version',
                ),
                migrations.RemoveConstraint(
                    model_name='datasettranslation',
                    name=_PREVIOUS_CONSTRAINT_PREFIX + 'null_version',
                ),
                migrations.AddConstraint(
                    model_name='datasettranslation',
                    constraint=models.UniqueConstraint(fields=('service', 'client_name', 'client_version'), name='uniq_dataset_translation_service_name_version'),
                ),
                migrations.AddConstraint(
                    model_name='datasettranslation',
                    constraint=models.UniqueConstraint(condition=models.Q(('client_version__isnull', True)), fields=('service', 'client_name'), name='uniq_dataset_translation_service_name_null_version'),
                ),
            ],
        ),
        migrations.AlterModelTable(
            name='datasettranslation',
            table='dataset_translation',
        ),
    ]
