# Generated by Django 5.2.17 on 2026-09-10 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_create_dsg_cache_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('allowed_services', models.JSONField(blank=True, default=list, help_text='reserved — not yet enforced')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='apikey',
            name='delegated_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='core.registeredclient'),
        ),
        migrations.CreateModel(
            name='ClientConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_consents', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.registeredclient')),
            ],
            options={
                'unique_together': {('user', 'client')},
            },
        ),
    ]
