# Generated by Django 5.2.11 on 2026-09-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_registered_clients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BucketIAMBinding',
        ),
    ]
